worker_processes 1;
events { worker_connections 1024; }

http {
    include mime.types;
    default_type application/octet-stream;

    limit_req_zone $binary_remote_addr zone=agent_limit:10m rate=10r/m;
    limit_req_zone $binary_remote_addr zone=general_limit:10m rate=120r/m;

 server {
        listen 80;
        # auth_basic "Restricted";
        # auth_basic_user_file /etc/nginx/.htpasswd;

        location /api/agent/ {
            limit_req zone=agent_limit burst=3 nodelay;
            proxy_pass http://ai_analytics_agent:8001/;
            proxy_set_header Host $host;
            proxy_read_timeout 120s;
        }

        location /api/forecast/ {
            limit_req zone=general_limit burst=10 nodelay;
            proxy_pass http://forecasting:8000/;
            proxy_set_header Host $host;
        }

        location / {
            limit_req zone=general_limit burst=20 nodelay;
            proxy_pass http://ui:80;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 8088;
        # auth_basic "Restricted";
        # auth_basic_user_file /etc/nginx/.htpasswd;
        limit_req zone=general_limit burst=30 nodelay;

        location / {
            proxy_pass http://superset:8088;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
