analytics_dbt:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: localhost
      pass:  "{{ env_var('DB_PASSWORD') }}"
      port: 5433
      schema: analytics_dbt
      threads: 4
      type: postgres
      user:  "{{ env_var('DB_USER') }}"
  target: dev
